export default {
	atomOneDark: {
		css: {
			"--tw-prose-body": "#abb2bf",
			"--tw-prose-headings": "#e06c75",
			"--tw-prose-lead": "#828997",
			"--tw-prose-links": "#61afef",
			"--tw-prose-bold": "#d19a66",
			"--tw-prose-counters": "#828997",
			"--tw-prose-bullets": "#56b6c2",
			"--tw-prose-hr": "#3e4451",
			"--tw-prose-quotes": "#98c379",
			"--tw-prose-quote-borders": "#3e4451",
			"--tw-prose-captions": "#828997",
			"--tw-prose-kbd": "#abb2bf",
			"--tw-prose-kbd-shadows": 'hexToRgb("#282c34")',
			"--tw-prose-code": "#c678dd",
			"--tw-prose-pre-code": "#abb2bf",
			"--tw-prose-pre-bg": "#282c34",
			"--tw-prose-th-borders": "#56b6c2",
			"--tw-prose-td-borders": "#3e4451",
			"--tw-prose-invert-body": "#abb2bf",
			"--tw-prose-invert-headings": "#e06c75",
			"--tw-prose-invert-lead": "#828997",
			"--tw-prose-invert-links": "#61afef",
			"--tw-prose-invert-bold": "#d19a66",
			"--tw-prose-invert-counters": "#828997",
			"--tw-prose-invert-bullets": "#56b6c2",
			"--tw-prose-invert-hr": "#3e4451",
			"--tw-prose-invert-quotes": "#98c379",
			"--tw-prose-invert-quote-borders": "#3e4451",
			"--tw-prose-invert-captions": "#828997",
			"--tw-prose-invert-kbd": "#abb2bf",
			"--tw-prose-invert-kbd-shadows": 'hexToRgb("#abb2bf")',
			"--tw-prose-invert-code": "#c678dd",
			"--tw-prose-invert-pre-code": "#abb2bf",
			"--tw-prose-invert-pre-bg": "rgb(40 44 52 / 50%)",
			"--tw-prose-invert-th-borders": "#56b6c2",
			"--tw-prose-invert-td-borders": "#3e4451",
		},
	},
};
