import { hexToRgb } from "./utils";

export default {
	catppuccin: {
		css: {
			"--tw-prose-body": "#4c4f69",
			"--tw-prose-headings": "#343637",
			"--tw-prose-lead": "#6c6f85",
			"--tw-prose-links": "#1e66f5",
			"--tw-prose-bold": "#343637",
			"--tw-prose-counters": "#8c8fa1",
			"--tw-prose-bullets": "#8839ef",
			"--tw-prose-hr": "#e6e9ef",
			"--tw-prose-quotes": "#343637",
			"--tw-prose-quote-borders": "#e6e9ef",
			"--tw-prose-captions": "#8c8fa1",
			"--tw-prose-kbd": "#343637",
			"--tw-prose-kbd-shadows": hexToRgb("#343637"),
			"--tw-prose-code": "#d20f39",
			"--tw-prose-pre-code": "#e6e9ef",
			"--tw-prose-pre-bg": "#4c4f69",
			"--tw-prose-th-borders": "#8839ef",
			"--tw-prose-td-borders": "#e6e9ef",

			"--tw-prose-invert-body": "#cdd6f4",
			"--tw-prose-invert-headings": "#ffffff",
			"--tw-prose-invert-lead": "#bac2de",
			"--tw-prose-invert-links": "#89b4fa",
			"--tw-prose-invert-bold": "#ffffff",
			"--tw-prose-invert-counters": "#9399b2",
			"--tw-prose-invert-bullets": "#b4befe",
			"--tw-prose-invert-hr": "#45475a",
			"--tw-prose-invert-quotes": "#ffffff",
			"--tw-prose-invert-quote-borders": "#45475a",
			"--tw-prose-invert-captions": "#9399b2",
			"--tw-prose-invert-kbd": "#ffffff",
			"--tw-prose-invert-kbd-shadows": hexToRgb("#ffffff"),
			"--tw-prose-invert-code": "#f38ba8",
			"--tw-prose-invert-pre-code": "#cdd6f4",
			"--tw-prose-invert-pre-bg": "rgb(76 79 105 / 50%)",
			"--tw-prose-invert-th-borders": "#b4befe",
			"--tw-prose-invert-td-borders": "#45475a",
		},
	},
};
